<a href="https://colab.research.google.com/github/anvitank/Data-Preprocessing/blob/main/exp12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Experiment 12
## Title: Data Wrangling
## 17 March 2026
## Anvi Singh Tank
## PRN: 25070123019
## ENTC A1

In [10]:
import pandas as pd
import numpy as np
df1=pd.DataFrame({'A1':[13,43,np.nan],'A2':[15,np.nan,np.nan],'A3':[10,20,30]})
df1

     A1    A2  A3
0  13.0  15.0  10
1  43.0   NaN  20
2   NaN   NaN  30

In [11]:
df1.isna() #Boolean Function

      A1     A2     A3
0  False  False  False
1  False   True  False
2   True   True  False

In [12]:
df1.notna() #Boolean Function

      A1     A2    A3
0   True   True  True
1   True  False  True
2  False  False  True

In [13]:
df1.isna().sum() #Columnwise na values

A1    1
A2    2
A3    0
dtype: int64

In [14]:
df1.dropna() # NaN rows are dropped

     A1    A2  A3
0  13.0  15.0  10

In [15]:
df1.fillna(value='DEFAULT')

        A1       A2  A3
0     13.0     15.0  10
1     43.0  DEFAULT  20
2  DEFAULT  DEFAULT  30

In [16]:
df1.fillna(df1.mean()) #Mean values of columns are calculated

     A1    A2  A3
0  13.0  15.0  10
1  43.0  15.0  20
2  28.0  15.0  30

In [17]:
data={
    "Roll No":[101,102,103,104,105],
      "Name":['Asha','Rohan','Meera','Karan','Anil'],
      'Age':[20,'-',21,20,'22'],
      'Marks':[85,90,'-',88,76],
      'Department':['CSE','IT','CSE','cse','E&TC'],
      'Admission_Date':['01-06-2023','03-06-2023','05-06-2023','07-06-2023','10/06/2023']
    }
df=pd.DataFrame(data)
df

df.to_csv('student_data.csv', index=False)

In [18]:
#Replace '-' with NaN to mark misssing values
df.replace("-", np.nan, inplace=True)
df

/tmp/ipykernel_1448/598201569.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("-", np.nan, inplace=True)

   Roll No   Name  Age  Marks Department Admission_Date
0      101   Asha   20   85.0        CSE     01-06-2023
1      102  Rohan  NaN   90.0         IT     03-06-2023
2      103  Meera   21    NaN        CSE     05-06-2023
3      104  Karan   20   88.0        cse     07-06-2023
4      105   Anil   22   76.0       E&TC     10/06/2023

In [19]:
#Convert Columns to numeric where needed
df['Age']=pd.to_numeric(df['Age'], errors='coerce')
df['Marks']=pd.to_numeric(df['Marks'], errors='coerce')
df

   Roll No   Name   Age  Marks Department Admission_Date
0      101   Asha  20.0   85.0        CSE     01-06-2023
1      102  Rohan   NaN   90.0         IT     03-06-2023
2      103  Meera  21.0    NaN        CSE     05-06-2023
3      104  Karan  20.0   88.0        cse     07-06-2023
4      105   Anil  22.0   76.0       E&TC     10/06/2023

In [20]:
#Check missing values
print('\nMissing values:')
print(df.isnull().sum())

Missing values:
Roll No           0
Name              0
Age               1
Marks             1
Department        0
Admission_Date    0
dtype: int64

In [21]:
#Fill missing age with mean
df['Age'].fillna(df['Age'].mean(), inplace=True)
df

/tmp/ipykernel_1448/3100345616.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)

   Roll No   Name    Age  Marks Department Admission_Date
0      101   Asha  20.00   85.0        CSE     01-06-2023
1      102  Rohan  20.75   90.0         IT     03-06-2023
2      103  Meera  21.00    NaN        CSE     05-06-2023
3      104  Karan  20.00   88.0        cse     07-06-2023
4      105   Anil  22.00   76.0       E&TC     10/06/2023

In [22]:
df['Marks'].fillna(df['Marks'].median(), inplace=True)
df

/tmp/ipykernel_1448/3187862212.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Marks'].fillna(df['Marks'].median(), inplace=True)

   Roll No   Name    Age  Marks Department Admission_Date
0      101   Asha  20.00   85.0        CSE     01-06-2023
1      102  Rohan  20.75   90.0         IT     03-06-2023
2      103  Meera  21.00   86.5        CSE     05-06-2023
3      104  Karan  20.00   88.0        cse     07-06-2023
4      105   Anil  22.00   76.0       E&TC     10/06/2023

In [23]:
#Fix inconsistent text formatting
df['Department']=df['Department'].str.upper()
df

   Roll No   Name    Age  Marks Department Admission_Date
0      101   Asha  20.00   85.0        CSE     01-06-2023
1      102  Rohan  20.75   90.0         IT     03-06-2023
2      103  Meera  21.00   86.5        CSE     05-06-2023
3      104  Karan  20.00   88.0        CSE     07-06-2023
4      105   Anil  22.00   76.0       E&TC     10/06/2023

In [24]:
#Convert Admission_Dat to standard datetime format
df['Admission_Date']=pd.to_datetime(df['Admission_Date'],errors='coerce')
df

   Roll No   Name    Age  Marks Department Admission_Date
0      101   Asha  20.00   85.0        CSE     2023-01-06
1      102  Rohan  20.75   90.0         IT     2023-03-06
2      103  Meera  21.00   86.5        CSE     2023-05-06
3      104  Karan  20.00   88.0        CSE     2023-07-06
4      105   Anil  22.00   76.0       E&TC            NaT

In [25]:
print('Cleaned data')
df

Cleaned data

   Roll No   Name    Age  Marks Department Admission_Date
0      101   Asha  20.00   85.0        CSE     2023-01-06
1      102  Rohan  20.75   90.0         IT     2023-03-06
2      103  Meera  21.00   86.5        CSE     2023-05-06
3      104  Karan  20.00   88.0        CSE     2023-07-06
4      105   Anil  22.00   76.0       E&TC            NaT

In [26]:
df.to_csv('cleaned_studet_data.csv', index=False)
print('Cleaned csv saed as cleaned_studet_data.csv')

Cleaned csv saed as cleaned_studet_data.csv

In [28]:
df=pd.read_csv('/content/Cars93 (3).csv')
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [29]:
#Check for missing value
df.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [30]:
#Inputing the missing value
df['Luggage.room'].mean()

np.float64(13.890243902439025)

In [31]:
df['Luggage.room'].median()

14.0

In [32]:
df['Luggage.room']=df['Luggage.room'].fillna(df['Luggage.room'].mean())

In [33]:
df.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [34]:
df['Rear.seat.room'].mean()

np.float64(27.82967032967033)

In [35]:
df['Rear.seat.room'].median()

27.5

In [36]:
df['Rear.seat.room']=df['Rear.seat.room'].fillna(df['Rear.seat.room'].mean())

In [37]:
df.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [38]:
df['AirBags']=df['AirBags'].fillna(df['AirBags'].mode().values[0])
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5,11.000000
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.000000
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.000000
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.000000
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.000000
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,Driver only,109,7,34.0,13.890244
89,Volkswagen,Passat,Compact,20.0,21,Driver only,134,5,31.5,14.000000
90,Volkswagen,Corrado,Sporty,23.3,18,Driver only,178,4,26.0,15.000000
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.000000
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.000000

In [39]:
df.isna().sum()

Manufacturer      0
Model             0
Type              0
Price             0
MPG.city          0
AirBags           0
Horsepower        0
Passengers        0
Rear.seat.room    0
Luggage.room      0
dtype: int64

In [48]:
print(df.head())
print(df.tail())

   Fruits    Calories  Weight  Taste  Price DateOfPurchace
0   APPLE  420.000000    40.0  sweet   70.0     2023-03-12
1  BANANA  380.000000    40.0  sweet   40.0     2020-01-06
2   MANGO  336.666667    70.0   sour   70.0     03-01-2025
3  GRAPES  210.000000     3.0   sour  100.0     2026/02/12
   Fruits    Calories  Weight  Taste  Price DateOfPurchace
0   APPLE  420.000000    40.0  sweet   70.0     2023-03-12
1  BANANA  380.000000    40.0  sweet   40.0     2020-01-06
2   MANGO  336.666667    70.0   sour   70.0     03-01-2025
3  GRAPES  210.000000     3.0   sour  100.0     2026/02/12

In [49]:
df.to_csv("CleanedCarsData.csv",index=False)
print(df)

   Fruits    Calories  Weight  Taste  Price DateOfPurchace
0   APPLE  420.000000    40.0  sweet   70.0     2023-03-12
1  BANANA  380.000000    40.0  sweet   40.0     2020-01-06
2   MANGO  336.666667    70.0   sour   70.0     03-01-2025
3  GRAPES  210.000000     3.0   sour  100.0     2026/02/12

In [40]:
import pandas as pd

NewData = {
    "Fruits" : ["Apple","Banana","Mango","Grapes"],
    "Calories" : [420,380,"_",210],
    "Weight" : ["_",40,70,3],
    "Taste" : ["Sweet","Sweet","Sour","Sour"],
    "Price" : [70,40,"_",100],
    "DateOfPurchace" : ["2023-03-12","2020-01-06","03-01-2025","2026/02/12"]
}

df = pd.DataFrame(NewData)
print("Original DataFrame:")
df.to_csv("Fruits.csv",index=False)
print(df)

Original DataFrame:
   Fruits Calories Weight  Taste Price DateOfPurchace
0   Apple      420      _  Sweet    70     2023-03-12
1  Banana      380     40  Sweet    40     2020-01-06
2   Mango        _     70   Sour     _     03-01-2025
3  Grapes      210      3   Sour   100     2026/02/12

In [41]:
import numpy as np

df.replace("_",np.nan,inplace=True)
print(df)

   Fruits  Calories  Weight  Taste  Price DateOfPurchace
0   Apple     420.0     NaN  Sweet   70.0     2023-03-12
1  Banana     380.0    40.0  Sweet   40.0     2020-01-06
2   Mango       NaN    70.0   Sour    NaN     03-01-2025
3  Grapes     210.0     3.0   Sour  100.0     2026/02/12

/tmp/ipykernel_1448/84087974.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("_",np.nan,inplace=True)

In [42]:
df["Calories"]=pd.to_numeric(df["Calories"],errors="coerce")
df["Weight"]=pd.to_numeric(df["Weight"],errors="coerce")
df["Price"]=pd.to_numeric(df["Price"],errors="coerce")
print(df)

   Fruits  Calories  Weight  Taste  Price DateOfPurchace
0   Apple     420.0     NaN  Sweet   70.0     2023-03-12
1  Banana     380.0    40.0  Sweet   40.0     2020-01-06
2   Mango       NaN    70.0   Sour    NaN     03-01-2025
3  Grapes     210.0     3.0   Sour  100.0     2026/02/12

In [43]:
print(df.isnull().sum())

Fruits            0
Calories          1
Weight            1
Taste             0
Price             1
DateOfPurchace    0
dtype: int64

In [44]:
print(df["Calories"].fillna(df["Calories"].mean(),inplace=True))
print(df["Weight"].fillna(df["Weight"].median(),inplace=True))
print(df["Price"].fillna(df["Price"].mean(),inplace=True))

None
None
None

/tmp/ipykernel_1448/4269353898.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  print(df["Calories"].fillna(df["Calories"].mean(),inplace=True))
/tmp/ipykernel_1448/4269353898.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  print(df["Weight"].fillna(df["Weight"].median(),inplace=True))
/tmp/ipykernel_1448/4269353898.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  print(df["Price"].fillna(df["Price"].mean(),inplace=True))

In [45]:
df["Fruits"] = df["Fruits"].str.upper()
df["Taste"] = df["Taste"].str.lower()
df

   Fruits    Calories  Weight  Taste  Price DateOfPurchace
0   APPLE  420.000000    40.0  sweet   70.0     2023-03-12
1  BANANA  380.000000    40.0  sweet   40.0     2020-01-06
2   MANGO  336.666667    70.0   sour   70.0     03-01-2025
3  GRAPES  210.000000     3.0   sour  100.0     2026/02/12

In [46]:
print("Cleaned data : \n",df)
df.to_csv("CleanedData.csv",index=False)

Cleaned data :
    Fruits    Calories  Weight  Taste  Price DateOfPurchace
0   APPLE  420.000000    40.0  sweet   70.0     2023-03-12
1  BANANA  380.000000    40.0  sweet   40.0     2020-01-06
2   MANGO  336.666667    70.0   sour   70.0     03-01-2025
3  GRAPES  210.000000     3.0   sour  100.0     2026/02/12